### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by heeler**
I got the tests running and building. The fix ended up being a minimal change to the config (travis.yml). There are a few other minor things like changing folder names and changing a few test file paths but that's it for the merge.

### CODE REVIEW

**Comment by donovanr** [comment]
damn setting up CI is such a pita.  the only thing i see that i don't love is that there's nowa binary file dependency.  is there a way to remove that?  like can you make the h5ad file on the fly and still have a meaningfull test.  that could be either generating it programmatically, or committing (small?) json/csv files and building and anndata object and then serializing it during the test.  i don;t like binary files in repos because they're big and lack transparency. thoughts?

**Comment by heeler** [comment]
It's a fair point. I basically just grabbed a snippet of the data (first 5 rows) and wrote it out as an annData object. I know having binary data in a repo is lame but it was expedient. I'll take a shot at programmatically creating an h5ad file and then using that.

**Comment by heeler** [comment]
So there's now a class that constructs random data that mocks a real dataset.
The Var mimick protein names ABCD_HUMAN
The obj mimick sequence names E1_AAATTTTGGGGCCCC_9_32
The x block are random values
Vars do have a gene.mean value and a gene.dispersion value as well (both random floats)
I've removed the binary data file from the repo so it's cleaner. Assuming the build and test runs through I'll merge this back into master.

**Comment by donovanr** [comment]
merged this but left the branch – @heeler you can delete it if you're done with it

**Pull request merged**
