### PR TITLE
GSDataset

### PR DESCRIPTION
**Pull request by heeler**
There are some ide files to ignore but the database.py and database_test.py implement the functionality. I haven't implemented add yet but I intend to. When the class is initialized it can be configured to return either a Tensor or an ndarray or a tuple (ndarray(objs), Tensor | ndarray ).

### CODE REVIEW

**Comment by donovanr** [comment]
bunch of `.idea/*` files... i'm guessing those aren't supposed to have been committed?

**Comment by donovanr** [comment]
@heeler can you make a branch on this repo and paste the `.py` files into it so i can pull it and see how it works?

**Comment by heeler** [comment]
> @heeler can you make a branch on this repo and paste the `.py` files into it so i can pull it and see how it works?

Will do. I'm just checking it the larger AnnData file you referenced yesterday.

**Review by donovanr — CHANGES_REQUESTED** [review]
`.py` files look like they're worth pushing to a test brach so we can try them out -- i think you can change the target branch to be something else: https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/

**Comment by gregjohnso** [comment]
All good with the exception of all of those `.idea/*` files. Maybe `.idea/*` should be added to the `.gitignore`.

**Review by gregjohnso — CHANGES_REQUESTED** [review]
remove .idea files, and maybe add those to the .gitignore

**Pull request closed without merging**
